/**
 * YAGOO Agent Database
 * 56 agents across 10 categories
 * Generated from directory.json
 */

export interface McpConfig {
  /** npx command to run the MCP server */
  command: string;
  /** Arguments to pass to the command */
  args: string[];
  /** Environment variables required */
  env?: Record<string, string>;
  /** Description of what this MCP server provides */
  description?: string;
}

export interface Agent {
  name: string;
  slug: string;
  tagline: string;
  description: string;
  primary_category: string;
  secondary_categories: string[];
  tags: string[];
  url: string;
  access_methods: string[];
  pricing_model: string;
  pricing_details: string;
  open_source: boolean;
  repo_url: string | null;
  underlying_model: string | null;
  capabilities: string[];
  limitations: string[];
  best_for: string[];
  not_ideal_for: string[];
  autonomy_level: string;
  reliability_notes: string;
  integrates_with: string[];
  mcp_support: boolean;
  /** MCP server configuration if available */
  mcp_config?: McpConfig;
  verified: boolean;
}

export const CATEGORY_LABELS: Record<string, string> = {
  coding_development: "Coding & Development",
  browser_web_automation: "Browser & Web Automation",
  research_analysis: "Research & Analysis",
  writing_content: "Writing & Content",
  creative_design: "Creative & Design",
  data_files: "Data & Files",
  communication_scheduling: "Communication & Scheduling",
  business_operations: "Business & Operations",
  personal_productivity: "Personal & Productivity",
  infrastructure_tools: "Infrastructure & Tools"
};

export const AGENTS: Agent[] = [
  {
    name: "Claude Code",
    slug: "claude-code",
    tagline: "Command-line AI coding agent from Anthropic",
    description: "Agentic coding tool that runs in your terminal. Can edit files, run commands, and handle multi-step development tasks with full codebase awareness.",
    primary_category: "coding_development",
    secondary_categories: [],
    tags: ["cli", "terminal", "agentic", "refactoring", "debugging"],
    url: "https://docs.anthropic.com/en/docs/claude-code",
    access_methods: ["cli"],
    pricing_model: "paid",
    pricing_details: "Usage-based API pricing",
    open_source: false,
    repo_url: null,
    underlying_model: "Claude",
    capabilities: ["Edit files across codebase", "Run terminal commands", "Multi-step development tasks", "Git operations", "Debugging and refactoring"],
    limitations: ["Requires API key", "Command-line comfort required", "No GUI"],
    best_for: ["Agentic coding tasks", "Refactoring large codebases", "Debugging in terminal", "Developers who prefer CLI"],
    not_ideal_for: ["Users unfamiliar with terminal", "Quick inline completions"],
    autonomy_level: "semi_autonomous",
    reliability_notes: "Highly reliable for coding tasks. Asks for confirmation on destructive operations.",
    integrates_with: ["Git", "GitHub", "Terminal"],
    mcp_support: true,
    verified: true
  },
  {
    name: "Cursor",
    slug: "cursor",
    tagline: "The AI-first code editor",
    description: "VS Code fork with deep AI integration. Codebase-aware completions, chat, and multi-file editing built into the editor experience.",
    primary_category: "coding_development",
    secondary_categories: [],
    tags: ["ide", "editor", "completions", "chat", "codebase-aware"],
    url: "https://cursor.com",
    access_methods: ["desktop_app"],
    pricing_model: "freemium",
    pricing_details: "Free tier available. Pro: $20/mo",
    open_source: false,
    repo_url: null,
    underlying_model: "GPT-4, Claude (user choice)",
    capabilities: ["Codebase-aware completions", "Multi-file editing", "Chat with codebase context", "Tab completions", "Inline editing"],
    limitations: ["IDE lock-in", "Can be resource-heavy", "Requires desktop app"],
    best_for: ["Daily coding with AI assistance", "Developers who want AI in their editor", "Codebase-aware completions"],
    not_ideal_for: ["Users committed to other IDEs", "Lightweight editing needs"],
    autonomy_level: "copilot",
    reliability_notes: "Generally reliable. Completions quality varies by codebase size.",
    integrates_with: ["Git", "GitHub", "VS Code extensions"],
    mcp_support: false,
    verified: true
  },
  {
    name: "Devin",
    slug: "devin",
    tagline: "The first AI software engineer",
    description: "Fully autonomous AI software engineer that can plan, code, debug, and deploy. Handles complex multi-step development tasks independently.",
    primary_category: "coding_development",
    secondary_categories: [],
    tags: ["autonomous", "software-engineer", "multi-step", "enterprise"],
    url: "https://devin.ai",
    access_methods: ["chat_ui", "api"],
    pricing_model: "enterprise",
    pricing_details: "Enterprise pricing. Contact sales.",
    open_source: false,
    repo_url: null,
    underlying_model: "Custom",
    capabilities: ["Autonomous task planning", "Multi-step development", "Debugging", "Deployment", "Learning from feedback"],
    limitations: ["Expensive", "Best for larger tasks, not quick fixes", "Enterprise-focused"],
    best_for: ["Autonomous multi-step development", "Complex feature implementation", "Teams wanting to offload entire tasks"],
    not_ideal_for: ["Quick fixes", "Budget-conscious teams", "Simple coding tasks"],
    autonomy_level: "fully_autonomous",
    reliability_notes: "Can handle complex tasks but requires clear specifications.",
    integrates_with: ["GitHub", "Slack", "Linear"],
    mcp_support: false,
    verified: true
  },
  {
    name: "Aider",
    slug: "aider",
    tagline: "AI pair programming in your terminal",
    description: "Open source CLI tool for AI pair programming. Git-aware, supports multiple models, and edits files directly in your repo.",
    primary_category: "coding_development",
    secondary_categories: [],
    tags: ["cli", "open-source", "git-aware", "pair-programming"],
    url: "https://aider.chat",
    access_methods: ["cli"],
    pricing_model: "open_source",
    pricing_details: "Free. Bring your own API key.",
    open_source: true,
    repo_url: "https://github.com/paul-gauthier/aider",
    underlying_model: "GPT-4, Claude, others (user choice)",
    capabilities: ["Git-aware code editing", "Multi-file changes", "Automatic commits", "Voice coding", "Multiple model support"],
    limitations: ["Requires command line comfort", "Bring your own API key", "No GUI"],
    best_for: ["Git-aware code editing", "Local development", "Developers who want open source"],
    not_ideal_for: ["Users unfamiliar with terminal", "Those wanting turnkey solution"],
    autonomy_level: "copilot",
    reliability_notes: "Very reliable. Active development and community.",
    integrates_with: ["Git", "GitHub", "GitLab"],
    mcp_support: true,
    mcp_config: {
      command: "npx",
      args: ["-y", "@modelcontextprotocol/server-git"],
      description: "Git operations: read, search, and manipulate Git repositories."
    },
    verified: true
  },
  {
    name: "GitHub Copilot",
    slug: "github-copilot",
    tagline: "Your AI pair programmer",
    description: "AI code completion tool that integrates into popular IDEs. Suggests code as you type with broad language support.",
    primary_category: "coding_development",
    secondary_categories: [],
    tags: ["ide-extension", "completions", "inline", "microsoft"],
    url: "https://github.com/features/copilot",
    access_methods: ["browser_extension", "desktop_app"],
    pricing_model: "paid",
    pricing_details: "Individual: $10/mo. Business: $19/mo",
    open_source: false,
    repo_url: null,
    underlying_model: "OpenAI Codex",
    capabilities: ["Inline code completion", "Multi-language support", "IDE integration", "Code explanation", "Test generation"],
    limitations: ["Less agentic than alternatives", "More autocomplete-focused", "Subscription required"],
    best_for: ["Inline code completion", "Developers in VS Code/JetBrains", "Broad language support"],
    not_ideal_for: ["Multi-step agentic tasks", "Complex refactoring"],
    autonomy_level: "copilot",
    reliability_notes: "Very reliable for completions. Quality varies by language.",
    integrates_with: ["VS Code", "JetBrains", "Neovim", "GitHub"],
    mcp_support: true,
    mcp_config: {
      command: "npx",
      args: ["-y", "@modelcontextprotocol/server-github"],
      env: { "GITHUB_PERSONAL_ACCESS_TOKEN": "your-github-token" },
      description: "GitHub API access: repos, issues, PRs, code search."
    },
    verified: true
  },
  {
    name: "Codeium",
    slug: "codeium",
    tagline: "Free AI code completion",
    description: "AI code completion tool with free tier. Supports 70+ languages and integrates with popular IDEs.",
    primary_category: "coding_development",
    secondary_categories: [],
    tags: ["code-completion", "free", "ide", "autocomplete", "multi-language"],
    url: "https://codeium.com",
    access_methods: ["browser_extension", "desktop_app"],
    pricing_model: "freemium",
    pricing_details: "Free for individuals. Teams: $12/mo per seat.",
    open_source: false,
    repo_url: null,
    underlying_model: "Custom",
    capabilities: ["Code completion", "70+ language support", "IDE integration", "Chat interface", "Code explanation"],
    limitations: ["Less context-aware than Copilot", "Newer product", "Enterprise features limited"],
    best_for: ["Developers wanting free AI", "Multi-language projects", "Those priced out of Copilot"],
    not_ideal_for: ["Enterprise security requirements", "Those wanting best-in-class"],
    autonomy_level: "copilot",
    reliability_notes: "Reliable completions. Free tier is generous.",
    integrates_with: ["VS Code", "JetBrains", "Vim", "Emacs"],
    mcp_support: false,
    verified: true
  },
  {
    name: "Tabnine",
    slug: "tabnine",
    tagline: "AI code assistant with privacy focus",
    description: "AI code completion that can run locally. Enterprise-focused with strong privacy and security features.",
    primary_category: "coding_development",
    secondary_categories: [],
    tags: ["code-completion", "privacy", "local", "enterprise", "security"],
    url: "https://tabnine.com",
    access_methods: ["browser_extension", "desktop_app"],
    pricing_model: "freemium",
    pricing_details: "Free tier. Pro: $12/mo. Enterprise available.",
    open_source: false,
    repo_url: null,
    underlying_model: "Custom (can run locally)",
    capabilities: ["Code completion", "Local/private deployment", "Team learning", "IDE integration"],
    limitations: ["Less powerful than cloud options when local", "Enterprise focus"],
    best_for: ["Privacy-conscious teams", "Enterprises with security requirements", "Air-gapped environments"],
    not_ideal_for: ["Those wanting best completions regardless of privacy", "Individual hobbyists"],
    autonomy_level: "copilot",
    reliability_notes: "Very reliable. Strong enterprise track record.",
    integrates_with: ["VS Code", "JetBrains", "Sublime", "Vim"],
    mcp_support: false,
    verified: true
  },
  {
    name: "Replit Agent",
    slug: "replit-agent",
    tagline: "AI that builds apps from description",
    description: "Describe what you want to build and Replit Agent creates it. Full stack development from natural language.",
    primary_category: "coding_development",
    secondary_categories: [],
    tags: ["no-code", "app-building", "full-stack", "deployment", "beginner-friendly"],
    url: "https://replit.com",
    access_methods: ["chat_ui"],
    pricing_model: "freemium",
    pricing_details: "Free tier. Pro: $20/mo. Teams available.",
    open_source: false,
    repo_url: null,
    underlying_model: "Custom",
    capabilities: ["Full app creation from description", "Frontend and backend", "Database setup", "Deployment", "Iterative refinement"],
    limitations: ["Replit platform only", "Complex apps need guidance", "Less control than manual coding"],
    best_for: ["Rapid prototyping", "Non-developers building apps", "Learning to code"],
    not_ideal_for: ["Production enterprise apps", "Specific tech stack requirements"],
    autonomy_level: "fully_autonomous",
    reliability_notes: "Good for prototypes. Production use requires review.",
    integrates_with: ["Replit platform", "GitHub"],
    mcp_support: false,
    verified: true
  },
  {
    name: "v0",
    slug: "v0",
    tagline: "AI UI generator from Vercel",
    description: "Generate React components and UI from descriptions. Creates shadcn/ui components with Tailwind CSS.",
    primary_category: "coding_development",
    secondary_categories: ["creative_design"],
    tags: ["ui", "react", "components", "frontend", "design-to-code"],
    url: "https://v0.dev",
    access_methods: ["chat_ui"],
    pricing_model: "freemium",
    pricing_details: "Free credits. Premium for more generations.",
    open_source: false,
    repo_url: null,
    underlying_model: "Custom",
    capabilities: ["UI component generation", "React/Next.js output", "shadcn/ui components", "Responsive design"],
    limitations: ["UI focused, not full apps", "Vercel/React ecosystem", "Credit-based"],
    best_for: ["Frontend developers", "UI prototyping", "React/Next.js projects"],
    not_ideal_for: ["Backend development", "Non-React projects"],
    autonomy_level: "copilot",
    reliability_notes: "Very reliable for UI generation. Clean, usable output.",
    integrates_with: ["Vercel", "Next.js", "React"],
    mcp_support: false,
    verified: true
  },
  {
    name: "Bolt",
    slug: "bolt",
    tagline: "AI full-stack app builder",
    description: "Build and deploy full-stack web applications through conversation. Creates React apps with backend and database.",
    primary_category: "coding_development",
    secondary_categories: [],
    tags: ["full-stack", "app-builder", "deployment", "no-code", "web-apps"],
    url: "https://bolt.new",
    access_methods: ["chat_ui"],
    pricing_model: "freemium",
    pricing_details: "Free tier with limits. Pro plans available.",
    open_source: false,
    repo_url: null,
    underlying_model: "Claude",
    capabilities: ["Full-stack app generation", "Real-time preview", "Database integration", "Deployment"],
    limitations: ["Web apps only", "Platform-specific deployment", "Complex apps need refinement"],
    best_for: ["Rapid prototyping", "MVPs", "Developers wanting speed"],
    not_ideal_for: ["Mobile apps", "Highly custom requirements"],
    autonomy_level: "semi_autonomous",
    reliability_notes: "Good for prototypes. Quality improving rapidly.",
    integrates_with: ["Various deployment platforms"],
    mcp_support: false,
    verified: true
  },
  {
    name: "Claude Computer Use",
    slug: "claude-computer-use",
    tagline: "AI that can see your screen and control your browser",
    description: "Claude with the ability to take screenshots, click, type, and navigate desktop applications and browsers.",
    primary_category: "browser_web_automation",
    secondary_categories: ["coding_development", "data_files"],
    tags: ["browser", "automation", "screenshot", "desktop", "forms"],
    url: "https://claude.ai",
    access_methods: ["chat_ui", "api"],
    pricing_model: "freemium",
    pricing_details: "Free tier available. Pro: $20/mo. API: usage-based",
    open_source: false,
    repo_url: null,
    underlying_model: "Claude Sonnet/Opus",
    capabilities: ["Browse websites", "Take screenshots", "Click and type", "Fill forms", "Navigate applications", "Create and edit files", "Execute code"],
    limitations: ["Cannot bypass authentication without user help", "Screenshot-based", "Rate limited on complex tasks"],
    best_for: ["Web research and data gathering", "Automating repetitive browser tasks", "Creating documents and files", "Multi-step workflows"],
    not_ideal_for: ["Real-time trading", "Tasks requiring persistent login", "High-volume scraping"],
    autonomy_level: "semi_autonomous",
    reliability_notes: "Generally reliable. Can struggle with CAPTCHAs.",
    integrates_with: ["Google Drive", "Framer", "Web browsers"],
    mcp_support: true,
    verified: true
  },
  {
    name: "Browser Use",
    slug: "browser-use",
    tagline: "Open source browser automation for AI agents",
    description: "Python library for building AI agents that can control browsers. Provides infrastructure for custom browser automation.",
    primary_category: "browser_web_automation",
    secondary_categories: ["infrastructure_tools"],
    tags: ["open-source", "python", "library", "diy", "customizable"],
    url: "https://github.com/browser-use/browser-use",
    access_methods: ["sdk"],
    pricing_model: "open_source",
    pricing_details: "Free. Open source.",
    open_source: true,
    repo_url: "https://github.com/browser-use/browser-use",
    underlying_model: "Bring your own",
    capabilities: ["Browser control via Python", "Customizable workflows", "Headless or headed operation", "Integration with any LLM"],
    limitations: ["Requires coding", "Self-hosted", "DIY setup"],
    best_for: ["DIY browser automation", "Custom workflows", "Developers building agents"],
    not_ideal_for: ["Non-technical users", "Quick one-off tasks"],
    autonomy_level: "fully_autonomous",
    reliability_notes: "Reliability depends on implementation. Active open source project.",
    integrates_with: ["Playwright", "Any LLM API"],
    mcp_support: true,
    mcp_config: {
      command: "npx",
      args: ["-y", "@playwright/mcp@latest"],
      description: "Browser automation via Playwright. Enables web navigation, form filling, screenshots."
    },
    verified: true
  },
  {
    name: "Operator",
    slug: "openai-operator",
    tagline: "OpenAI's browser agent",
    description: "OpenAI's autonomous browser agent integrated into ChatGPT Pro. Can browse the web and complete complex tasks.",
    primary_category: "browser_web_automation",
    secondary_categories: ["research_analysis"],
    tags: ["openai", "browser", "autonomous", "premium"],
    url: "https://openai.com/operator",
    access_methods: ["chat_ui"],
    pricing_model: "paid",
    pricing_details: "$200/mo (ChatGPT Pro subscription required)",
    open_source: false,
    repo_url: null,
    underlying_model: "GPT-4",
    capabilities: ["Autonomous web browsing", "Complex multi-step tasks", "Form filling", "Research and data gathering"],
    limitations: ["Expensive ($200/mo)", "Limited availability", "ChatGPT Pro required"],
    best_for: ["Complex web tasks", "Users already on ChatGPT Pro", "Integrated GPT-4 experience"],
    not_ideal_for: ["Budget-conscious users", "Simple browsing tasks"],
    autonomy_level: "fully_autonomous",
    reliability_notes: "New product. Reliability still being established.",
    integrates_with: ["ChatGPT"],
    mcp_support: false,
    verified: true
  },
  {
    name: "MultiOn",
    slug: "multion",
    tagline: "AI agent that browses the web for you",
    description: "Browser automation agent accessible via API and browser extension. Can perform web tasks like booking and purchasing.",
    primary_category: "browser_web_automation",
    secondary_categories: ["personal_productivity"],
    tags: ["browser", "automation", "booking", "purchasing", "api"],
    url: "https://multion.ai",
    access_methods: ["api", "browser_extension"],
    pricing_model: "paid",
    pricing_details: "Paid plans. Contact for pricing.",
    open_source: false,
    repo_url: null,
    underlying_model: "Custom",
    capabilities: ["Automated web tasks", "Booking and reservations", "Purchasing", "Form filling", "Web navigation"],
    limitations: ["Trust required for sensitive actions", "Paid only", "Limited transparency"],
    best_for: ["Automated booking", "Repetitive web tasks", "Developers building on browser automation"],
    not_ideal_for: ["Sensitive financial transactions", "Tasks requiring full user control"],
    autonomy_level: "fully_autonomous",
    reliability_notes: "Generally reliable for supported tasks.",
    integrates_with: ["Chrome"],
    mcp_support: false,
    verified: true
  },
  {
    name: "Perplexity",
    slug: "perplexity",
    tagline: "AI-powered answer engine",
    description: "Search engine that provides direct answers with sources. Combines web search with AI synthesis.",
    primary_category: "research_analysis",
    secondary_categories: [],
    tags: ["search", "research", "sources", "current-events", "quick"],
    url: "https://perplexity.ai",
    access_methods: ["chat_ui", "mobile_app", "api"],
    pricing_model: "freemium",
    pricing_details: "Free tier available. Pro: $20/mo",
    open_source: false,
    repo_url: null,
    underlying_model: "Multiple (GPT-4, Claude, custom)",
    capabilities: ["Web search with AI synthesis", "Sourced answers", "Current events", "Follow-up questions", "Collections for research"],
    limitations: ["Less deep than multi-step research agents", "Source quality varies", "Not for original analysis"],
    best_for: ["Quick research questions", "Current events", "Sourced factual answers"],
    not_ideal_for: ["Deep multi-step research", "Original analysis", "Academic rigor"],
    autonomy_level: "copilot",
    reliability_notes: "Very reliable for quick lookups.",
    integrates_with: ["Chrome extension", "Mobile"],
    mcp_support: true,
    mcp_config: {
      command: "npx",
      args: ["-y", "@anthropic/mcp-server-brave-search"],
      env: { "BRAVE_API_KEY": "your-brave-api-key" },
      description: "Web search via Brave Search API. Alternative to Perplexity for real-time info."
    },
    verified: true
  },
  {
    name: "Claude Deep Research",
    slug: "claude-deep-research",
    tagline: "Multi-step research that goes deep",
    description: "Claude's deep research mode that performs comprehensive, multi-step research on complex topics.",
    primary_category: "research_analysis",
    secondary_categories: ["writing_content"],
    tags: ["research", "deep", "multi-step", "reports", "comprehensive"],
    url: "https://claude.ai",
    access_methods: ["chat_ui"],
    pricing_model: "paid",
    pricing_details: "Pro subscription required ($20/mo)",
    open_source: false,
    repo_url: null,
    underlying_model: "Claude",
    capabilities: ["Multi-step web research", "Comprehensive reports", "Source synthesis", "Complex topic analysis"],
    limitations: ["Takes time (several minutes)", "Uses significant context", "Pro subscription required"],
    best_for: ["Comprehensive research reports", "Complex topics", "Due diligence"],
    not_ideal_for: ["Quick lookups", "Real-time information needs"],
    autonomy_level: "semi_autonomous",
    reliability_notes: "High quality output. Takes time but produces thorough results.",
    integrates_with: ["Claude.ai"],
    mcp_support: false,
    verified: true
  },
  {
    name: "Elicit",
    slug: "elicit",
    tagline: "AI research assistant for academic papers",
    description: "Research tool focused on academic literature. Helps with literature review, finding papers, and extracting information.",
    primary_category: "research_analysis",
    secondary_categories: [],
    tags: ["academic", "papers", "literature-review", "research", "science"],
    url: "https://elicit.com",
    access_methods: ["chat_ui"],
    pricing_model: "freemium",
    pricing_details: "Free tier available. Paid plans for more usage.",
    open_source: false,
    repo_url: null,
    underlying_model: "Custom",
    capabilities: ["Academic paper search", "Literature review", "Paper summarization", "Data extraction from papers", "Citation management"],
    limitations: ["Focused on academic content", "Less useful for non-academic research", "Paper database coverage varies"],
    best_for: ["Literature reviews", "Academic research", "Finding relevant papers"],
    not_ideal_for: ["General web research", "Non-academic topics", "Current events"],
    autonomy_level: "copilot",
    reliability_notes: "Reliable for academic search. Paper coverage depends on databases.",
    integrates_with: ["Semantic Scholar", "Academic databases"],
    mcp_support: false,
    verified: true
  },
  {
    name: "Claude",
    slug: "claude",
    tagline: "Anthropic's AI assistant",
    description: "General-purpose AI assistant known for nuanced writing, analysis, and helpfulness. Available via web, mobile, and API.",
    primary_category: "writing_content",
    secondary_categories: ["research_analysis", "coding_development"],
    tags: ["general", "writing", "analysis", "conversation", "anthropic"],
    url: "https://claude.ai",
    access_methods: ["chat_ui", "mobile_app", "api"],
    pricing_model: "freemium",
    pricing_details: "Free tier available. Pro: $20/mo. API: usage-based",
    open_source: false,
    repo_url: null,
    underlying_model: "Claude",
    capabilities: ["Long-form writing", "Analysis and reasoning", "Code generation", "Conversation", "Document understanding"],
    limitations: ["Knowledge cutoff", "No real-time data without tools", "Cannot take actions without computer use"],
    best_for: ["Long-form writing", "Nuanced analysis", "Coding assistance", "Complex reasoning"],
    not_ideal_for: ["Real-time information", "Tasks requiring web access (without tools)"],
    autonomy_level: "copilot",
    reliability_notes: "Highly reliable. Known for being helpful and harmless.",
    integrates_with: ["Many via MCP", "API integrations"],
    mcp_support: true,
    verified: true
  },
  {
    name: "ChatGPT",
    slug: "chatgpt",
    tagline: "OpenAI's conversational AI",
    description: "General-purpose AI assistant from OpenAI. Broad capabilities including conversation, writing, coding, and image generation.",
    primary_category: "writing_content",
    secondary_categories: ["research_analysis", "coding_development", "creative_design"],
    tags: ["general", "openai", "gpt4", "conversation", "plugins"],
    url: "https://chat.openai.com",
    access_methods: ["chat_ui", "mobile_app", "api"],
    pricing_model: "freemium",
    pricing_details: "Free tier (GPT-3.5). Plus: $20/mo. Pro: $200/mo",
    open_source: false,
    repo_url: null,
    underlying_model: "GPT-4",
    capabilities: ["General conversation", "Writing", "Coding", "Image generation (DALL-E)", "Web browsing", "Plugins/GPTs"],
    limitations: ["Can be verbose", "Occasional hallucinations", "Plugin quality varies"],
    best_for: ["General writing", "Broad capabilities", "Users wanting one tool for everything"],
    not_ideal_for: ["Tasks requiring specialized depth", "Users preferring concise responses"],
    autonomy_level: "copilot",
    reliability_notes: "Generally reliable. Quality varies by task type.",
    integrates_with: ["Many via plugins", "DALL-E", "Browsing"],
    mcp_support: false,
    verified: true
  },
  {
    name: "Jasper",
    slug: "jasper",
    tagline: "AI marketing and content platform",
    description: "AI writing platform focused on marketing content. Features brand voice training, templates, and team collaboration.",
    primary_category: "writing_content",
    secondary_categories: ["business_operations"],
    tags: ["marketing", "copywriting", "brand-voice", "teams", "enterprise"],
    url: "https://jasper.ai",
    access_methods: ["chat_ui"],
    pricing_model: "paid",
    pricing_details: "Starts around $39/mo. Enterprise plans available.",
    open_source: false,
    repo_url: null,
    underlying_model: "Multiple (GPT-4, Claude)",
    capabilities: ["Marketing copy", "Brand voice training", "Templates", "Team collaboration", "Campaign management"],
    limitations: ["Marketing-focused, less versatile", "More expensive than general AI", "Template-driven"],
    best_for: ["Marketing teams", "Brand-consistent content", "Team collaboration"],
    not_ideal_for: ["General writing", "Individual users", "Non-marketing content"],
    autonomy_level: "copilot",
    reliability_notes: "Reliable for marketing use cases. Brand voice consistency is a strength.",
    integrates_with: ["Surfer SEO", "Grammarly", "Browser extension"],
    mcp_support: false,
    verified: true
  },
  {
    name: "Copy.ai",
    slug: "copy-ai",
    tagline: "AI-powered copywriting",
    description: "Copywriting tool with templates for various content types. Focused on short-form marketing copy and social media.",
    primary_category: "writing_content",
    secondary_categories: [],
    tags: ["copywriting", "templates", "social-media", "ads", "short-form"],
    url: "https://copy.ai",
    access_methods: ["chat_ui"],
    pricing_model: "freemium",
    pricing_details: "Free tier available. Paid plans for more usage.",
    open_source: false,
    repo_url: null,
    underlying_model: "GPT-based",
    capabilities: ["Short-form copy", "Ad copy", "Social media posts", "Email subject lines", "Product descriptions"],
    limitations: ["Template-driven", "Less flexible than general AI", "Short-form focused"],
    best_for: ["Quick marketing copy", "Social media content", "Ad variations"],
    not_ideal_for: ["Long-form content", "Technical writing", "Complex analysis"],
    autonomy_level: "copilot",
    reliability_notes: "Reliable for template-based outputs.",
    integrates_with: ["Zapier"],
    mcp_support: false,
    verified: true
  },
  {
    name: "Wordtune",
    slug: "wordtune",
    tagline: "AI writing companion",
    description: "Rewrites and improves your text. Offers multiple alternatives for sentences to improve clarity and tone.",
    primary_category: "writing_content",
    secondary_categories: [],
    tags: ["rewriting", "editing", "tone", "clarity", "browser-extension"],
    url: "https://wordtune.com",
    access_methods: ["browser_extension", "chat_ui"],
    pricing_model: "freemium",
    pricing_details: "Free tier. Premium: $9.99/mo",
    open_source: false,
    repo_url: null,
    underlying_model: "Custom",
    capabilities: ["Sentence rewriting", "Tone adjustment", "Length modification", "Grammar fixes", "Multiple alternatives"],
    limitations: ["Sentence-level focus", "Not for long-form generation", "Limited free tier"],
    best_for: ["Improving existing writing", "Non-native English speakers", "Email and message polishing"],
    not_ideal_for: ["Long-form content creation", "Creative writing"],
    autonomy_level: "copilot",
    reliability_notes: "Very reliable for sentence-level improvements.",
    integrates_with: ["Chrome", "Google Docs", "Microsoft Word"],
    mcp_support: false,
    verified: true
  },
  {
    name: "Grammarly",
    slug: "grammarly",
    tagline: "AI writing assistant",
    description: "Grammar, spelling, style, and tone checker. Now includes AI writing assistance and generation.",
    primary_category: "writing_content",
    secondary_categories: [],
    tags: ["grammar", "editing", "style", "tone", "professional"],
    url: "https://grammarly.com",
    access_methods: ["browser_extension", "desktop_app", "mobile_app"],
    pricing_model: "freemium",
    pricing_details: "Free tier. Premium: $12/mo. Business plans.",
    open_source: false,
    repo_url: null,
    underlying_model: "Custom + GPT",
    capabilities: ["Grammar and spelling", "Style suggestions", "Tone detection", "AI writing assistance", "Plagiarism detection (premium)"],
    limitations: ["Premium features locked", "AI generation is newer", "Can be overly prescriptive"],
    best_for: ["Professional writing", "Non-native speakers", "Business communication"],
    not_ideal_for: ["Creative writing that breaks rules", "Those wanting AI generation focus"],
    autonomy_level: "copilot",
    reliability_notes: "Very reliable. Industry standard for grammar checking.",
    integrates_with: ["Everywhere (browser, desktop, mobile)"],
    mcp_support: false,
    verified: true
  },
  {
    name: "Writer",
    slug: "writer",
    tagline: "Enterprise AI writing platform",
    description: "AI writing platform for enterprises. Features style guides, brand voice, and team governance.",
    primary_category: "writing_content",
    secondary_categories: ["business_operations"],
    tags: ["enterprise", "brand-voice", "governance", "teams", "compliance"],
    url: "https://writer.com",
    access_methods: ["chat_ui", "api", "browser_extension"],
    pricing_model: "paid",
    pricing_details: "Team: $18/mo per user. Enterprise available.",
    open_source: false,
    repo_url: null,
    underlying_model: "Palmyra (custom)",
    capabilities: ["AI content generation", "Brand voice consistency", "Style guide enforcement", "Content governance", "Team collaboration"],
    limitations: ["Enterprise-focused pricing", "Setup for best results", "Not for individual use"],
    best_for: ["Enterprise content teams", "Brand consistency", "Regulated industries"],
    not_ideal_for: ["Individual writers", "Small teams", "Creative writing"],
    autonomy_level: "copilot",
    reliability_notes: "Enterprise-grade reliability. Strong governance features.",
    integrates_with: ["Chrome", "Google Docs", "Figma", "Contentful"],
    mcp_support: false,
    verified: true
  },
  {
    name: "Midjourney",
    slug: "midjourney",
    tagline: "AI image generation",
    description: "AI image generator known for high-quality artistic output. Creates images from text prompts.",
    primary_category: "creative_design",
    secondary_categories: [],
    tags: ["image", "art", "creative", "generation", "artistic"],
    url: "https://midjourney.com",
    access_methods: ["chat_ui"],
    pricing_model: "paid",
    pricing_details: "Starts at $10/mo",
    open_source: false,
    repo_url: null,
    underlying_model: "Midjourney",
    capabilities: ["High-quality image generation", "Artistic styles", "Image variations", "Upscaling", "Style mixing"],
    limitations: ["Discord-based (web is newer)", "No API", "Less control than some alternatives"],
    best_for: ["Artistic images", "Creative projects", "High-quality visuals"],
    not_ideal_for: ["Precise technical diagrams", "API integration", "Text-in-image accuracy"],
    autonomy_level: "copilot",
    reliability_notes: "Very reliable for artistic output.",
    integrates_with: ["Discord"],
    mcp_support: false,
    verified: true
  },
  {
    name: "DALL-E 3",
    slug: "dalle-3",
    tagline: "OpenAI's image generator",
    description: "OpenAI's image generation model integrated into ChatGPT. Known for following text prompts accurately.",
    primary_category: "creative_design",
    secondary_categories: [],
    tags: ["image", "openai", "text-accurate", "generation", "chatgpt"],
    url: "https://openai.com/dall-e-3",
    access_methods: ["chat_ui", "api"],
    pricing_model: "freemium",
    pricing_details: "Included in ChatGPT Plus. API: usage-based",
    open_source: false,
    repo_url: null,
    underlying_model: "DALL-E 3",
    capabilities: ["Text-accurate images", "ChatGPT integration", "Prompt understanding", "Style variety"],
    limitations: ["Style less distinctive than Midjourney", "Content restrictions", "Less artistic control"],
    best_for: ["Text-in-image accuracy", "ChatGPT users", "Quick image generation"],
    not_ideal_for: ["Highly artistic output", "Specific style matching"],
    autonomy_level: "copilot",
    reliability_notes: "Reliable. Good at following prompts.",
    integrates_with: ["ChatGPT", "OpenAI API"],
    mcp_support: false,
    verified: true
  },
  {
    name: "Runway",
    slug: "runway",
    tagline: "AI video generation and editing",
    description: "AI-powered video creation and editing platform. Generates videos from text/images.",
    primary_category: "creative_design",
    secondary_categories: [],
    tags: ["video", "generation", "editing", "creative", "motion"],
    url: "https://runway.ml",
    access_methods: ["chat_ui"],
    pricing_model: "freemium",
    pricing_details: "Free tier available. Paid plans for more credits.",
    open_source: false,
    repo_url: null,
    underlying_model: "Gen-2, Gen-3",
    capabilities: ["Text-to-video", "Image-to-video", "Video editing", "Motion brush", "Green screen"],
    limitations: ["Compute-intensive", "Credits-based", "Short clip lengths"],
    best_for: ["Video generation", "Creative projects", "Motion content"],
    not_ideal_for: ["Long-form video", "Real-time generation", "Budget-limited users"],
    autonomy_level: "copilot",
    reliability_notes: "Reliable for short clips. Quality improving rapidly.",
    integrates_with: ["Adobe", "Apple Motion"],
    mcp_support: false,
    verified: true
  },
  {
    name: "Suno",
    slug: "suno",
    tagline: "AI music generation",
    description: "AI music generator that creates complete songs with vocals, instruments, and lyrics from text prompts.",
    primary_category: "creative_design",
    secondary_categories: [],
    tags: ["music", "audio", "generation", "songs", "creative"],
    url: "https://suno.ai",
    access_methods: ["chat_ui"],
    pricing_model: "freemium",
    pricing_details: "Free tier available. Paid plans for more generations.",
    open_source: false,
    repo_url: null,
    underlying_model: "Suno",
    capabilities: ["Full song generation", "Vocals and instruments", "Custom lyrics", "Style specification", "Extend existing songs"],
    limitations: ["Copyright ambiguity", "Style range limited", "Commercial use unclear"],
    best_for: ["Creating songs quickly", "Music experimentation", "Content creators"],
    not_ideal_for: ["Professional music production", "Commercial licensing clarity"],
    autonomy_level: "copilot",
    reliability_notes: "Reliably generates music. Quality improving.",
    integrates_with: [],
    mcp_support: false,
    verified: true
  },
  {
    name: "Luma",
    slug: "luma",
    tagline: "AI video model",
    description: "Video generation model that creates realistic videos from text prompts. Known for Dream Machine.",
    primary_category: "creative_design",
    secondary_categories: [],
    tags: ["video", "generation", "ai-video", "dream-machine", "creative"],
    url: "https://lumalabs.ai",
    access_methods: ["chat_ui", "api"],
    pricing_model: "freemium",
    pricing_details: "Free tier available. Paid for more generations.",
    open_source: false,
    repo_url: null,
    underlying_model: "Dream Machine",
    capabilities: ["Text-to-video", "Image-to-video", "Realistic motion", "Scene generation", "Camera control"],
    limitations: ["Short clip lengths", "Queue times", "Credit-based"],
    best_for: ["Video prototyping", "Creative projects", "Marketing content"],
    not_ideal_for: ["Long-form video", "Precise control needs"],
    autonomy_level: "copilot",
    reliability_notes: "Quality varies but improving rapidly.",
    integrates_with: ["API integrations"],
    mcp_support: false,
    verified: true
  },
  {
    name: "ElevenLabs",
    slug: "elevenlabs",
    tagline: "AI voice generation",
    description: "Text-to-speech with realistic voices. Create custom voices, clone voices, and generate natural speech.",
    primary_category: "creative_design",
    secondary_categories: [],
    tags: ["voice", "audio", "text-to-speech", "voice-cloning", "narration"],
    url: "https://elevenlabs.io",
    access_methods: ["chat_ui", "api"],
    pricing_model: "freemium",
    pricing_details: "Free tier. Starter: $5/mo. Creator: $22/mo",
    open_source: false,
    repo_url: null,
    underlying_model: "ElevenLabs",
    capabilities: ["Text-to-speech", "Voice cloning", "Multiple languages", "Voice design", "Audio projects"],
    limitations: ["Character limits on free tier", "Voice cloning requires consent", "Processing time for long audio"],
    best_for: ["Narration and audiobooks", "Video voiceovers", "Accessibility"],
    not_ideal_for: ["Real-time conversation", "Free high-volume use"],
    autonomy_level: "copilot",
    reliability_notes: "Industry-leading quality. Very reliable.",
    integrates_with: ["API", "Various content tools"],
    mcp_support: false,
    verified: true
  },
  {
    name: "Heygen",
    slug: "heygen",
    tagline: "AI video generation with avatars",
    description: "Create videos with AI avatars. Generate talking head videos from text without cameras or actors.",
    primary_category: "creative_design",
    secondary_categories: ["business_operations"],
    tags: ["video", "avatars", "talking-head", "marketing", "training"],
    url: "https://heygen.com",
    access_methods: ["chat_ui"],
    pricing_model: "freemium",
    pricing_details: "Free trial. Creator: $29/mo. Business plans.",
    open_source: false,
    repo_url: null,
    underlying_model: "Custom",
    capabilities: ["AI avatar videos", "Text-to-video", "Custom avatars", "Multi-language", "Video translation"],
    limitations: ["Avatar-based (not general video)", "Credit system", "Uncanny valley for some avatars"],
    best_for: ["Training videos", "Marketing content", "Localization"],
    not_ideal_for: ["Narrative video", "Non-talking-head content"],
    autonomy_level: "copilot",
    reliability_notes: "Reliable for avatar videos.",
    integrates_with: ["Various video platforms"],
    mcp_support: false,
    verified: true
  },
  {
    name: "Stability AI",
    slug: "stability-ai",
    tagline: "Open AI models for images, video, and audio",
    description: "Company behind Stable Diffusion. Offers image, video, and audio generation models.",
    primary_category: "creative_design",
    secondary_categories: ["infrastructure_tools"],
    tags: ["open-source", "image", "video", "audio", "models"],
    url: "https://stability.ai",
    access_methods: ["api", "sdk"],
    pricing_model: "freemium",
    pricing_details: "Free models available. API pricing for commercial use.",
    open_source: true,
    repo_url: "https://github.com/Stability-AI",
    underlying_model: "Stable Diffusion, etc.",
    capabilities: ["Image generation", "Video generation", "Audio generation", "Open source models", "API access"],
    limitations: ["Requires technical setup for local", "Quality varies by model version", "Commercial licensing varies"],
    best_for: ["Developers building on AI", "Those wanting open models", "Custom implementations"],
    not_ideal_for: ["Non-technical users", "Those wanting turnkey solutions"],
    autonomy_level: "copilot",
    reliability_notes: "Model quality varies. Active development community.",
    integrates_with: ["Many via API and local deployment"],
    mcp_support: false,
    verified: true
  },
  {
    name: "Julius AI",
    slug: "julius-ai",
    tagline: "AI data analyst",
    description: "Data analysis tool that can work with spreadsheets, create visualizations, and perform statistical analysis.",
    primary_category: "data_files",
    secondary_categories: ["research_analysis"],
    tags: ["data", "analysis", "visualization", "spreadsheets", "statistics"],
    url: "https://julius.ai",
    access_methods: ["chat_ui"],
    pricing_model: "freemium",
    pricing_details: "Free tier available. Paid plans for more data.",
    open_source: false,
    repo_url: null,
    underlying_model: "Custom",
    capabilities: ["Data analysis", "Visualization creation", "Spreadsheet manipulation", "Statistical analysis", "Natural language queries"],
    limitations: ["Data upload limits on free tier", "Large dataset handling can be slow", "Focused on analysis, not data engineering"],
    best_for: ["Data analysis", "Creating charts and visualizations", "Working with spreadsheets"],
    not_ideal_for: ["Large-scale data engineering", "Real-time data processing"],
    autonomy_level: "copilot",
    reliability_notes: "Reliable for standard analysis tasks.",
    integrates_with: ["CSV", "Excel", "Google Sheets"],
    mcp_support: true,
    mcp_config: {
      command: "npx",
      args: ["-y", "@modelcontextprotocol/server-filesystem"],
      env: { "ALLOWED_DIRECTORIES": "/path/to/data" },
      description: "File system access for data analysis. Set ALLOWED_DIRECTORIES to your data folder."
    },
    verified: true
  },
  {
    name: "Reclaim",
    slug: "reclaim",
    tagline: "AI calendar management",
    description: "Automatically schedules your tasks, habits, and meetings. Finds optimal times and protects focus time.",
    primary_category: "communication_scheduling",
    secondary_categories: ["personal_productivity"],
    tags: ["calendar", "scheduling", "time-management", "productivity", "automation"],
    url: "https://reclaim.ai",
    access_methods: ["chat_ui", "browser_extension"],
    pricing_model: "freemium",
    pricing_details: "Free tier available. Pro: $8/mo. Team plans available.",
    open_source: false,
    repo_url: null,
    underlying_model: "Custom",
    capabilities: ["Smart scheduling", "Task time blocking", "Meeting scheduling", "Habit scheduling", "Calendar analytics"],
    limitations: ["Google Calendar focused", "Requires calendar access", "Learning period for best results"],
    best_for: ["Busy professionals", "Task time blocking", "Calendar optimization"],
    not_ideal_for: ["Simple calendar needs", "Non-Google Calendar users"],
    autonomy_level: "semi_autonomous",
    reliability_notes: "Very reliable. Gets smarter over time.",
    integrates_with: ["Google Calendar", "Slack", "Asana", "Todoist", "Linear"],
    mcp_support: false,
    verified: true
  },
  {
    name: "Motion",
    slug: "motion",
    tagline: "AI-powered calendar and project management",
    description: "Automatically plans your day by scheduling tasks around meetings. Combines calendar, tasks, and project management.",
    primary_category: "communication_scheduling",
    secondary_categories: ["personal_productivity"],
    tags: ["calendar", "tasks", "project-management", "automation", "planning"],
    url: "https://usemotion.com",
    access_methods: ["desktop_app", "mobile_app", "chat_ui"],
    pricing_model: "paid",
    pricing_details: "Individual: $19/mo. Team plans available.",
    open_source: false,
    repo_url: null,
    underlying_model: "Custom",
    capabilities: ["Automatic task scheduling", "Project management", "Meeting scheduling", "Deadline tracking", "Team coordination"],
    limitations: ["Paid only", "Opinionated workflow", "Requires buy-in to approach"],
    best_for: ["Overwhelmed professionals", "Task-heavy workloads", "Teams needing coordination"],
    not_ideal_for: ["Simple calendar needs", "Those preferring manual control"],
    autonomy_level: "semi_autonomous",
    reliability_notes: "Reliable scheduling. May need adjustment for preferences.",
    integrates_with: ["Google Calendar", "Outlook", "Zoom", "Slack"],
    mcp_support: false,
    verified: true
  },
  {
    name: "Calendly",
    slug: "calendly",
    tagline: "Scheduling automation platform",
    description: "Share your availability and let others book meetings. Eliminates back-and-forth scheduling emails.",
    primary_category: "communication_scheduling",
    secondary_categories: ["business_operations"],
    tags: ["scheduling", "meetings", "booking", "calendar", "automation"],
    url: "https://calendly.com",
    access_methods: ["chat_ui", "browser_extension", "mobile_app"],
    pricing_model: "freemium",
    pricing_details: "Free tier available. Pro: $12/mo. Teams: $16/mo",
    open_source: false,
    repo_url: null,
    underlying_model: null,
    capabilities: ["Meeting scheduling links", "Availability sharing", "Calendar integration", "Team scheduling", "Routing and round-robin"],
    limitations: ["Not AI-powered (automation only)", "Limited customization on free tier", "Requires others to book"],
    best_for: ["External meeting scheduling", "Sales teams", "Anyone tired of scheduling emails"],
    not_ideal_for: ["Internal scheduling", "Task management"],
    autonomy_level: "copilot",
    reliability_notes: "Very reliable. Industry standard for scheduling.",
    integrates_with: ["Google Calendar", "Outlook", "Zoom", "Salesforce", "HubSpot"],
    mcp_support: false,
    verified: true
  },
  {
    name: "Superhuman",
    slug: "superhuman",
    tagline: "The fastest email experience",
    description: "Email client with AI features for triage, writing, and productivity. Keyboard-first design for speed.",
    primary_category: "communication_scheduling",
    secondary_categories: ["personal_productivity"],
    tags: ["email", "productivity", "writing", "speed", "premium"],
    url: "https://superhuman.com",
    access_methods: ["desktop_app", "mobile_app"],
    pricing_model: "paid",
    pricing_details: "$30/mo",
    open_source: false,
    repo_url: null,
    underlying_model: "GPT-4",
    capabilities: ["AI email writing", "Email triage", "Instant reply suggestions", "Read receipts", "Keyboard shortcuts"],
    limitations: ["Expensive", "Gmail/Outlook only", "Learning curve for shortcuts"],
    best_for: ["High-volume emailers", "Productivity enthusiasts", "Executives and managers"],
    not_ideal_for: ["Light email users", "Budget-conscious users"],
    autonomy_level: "copilot",
    reliability_notes: "Very reliable. Premium product with premium support.",
    integrates_with: ["Gmail", "Outlook", "Salesforce"],
    mcp_support: false,
    verified: true
  },
  {
    name: "Lindy",
    slug: "lindy",
    tagline: "AI assistant that automates your workflows",
    description: "Build custom AI employees that handle email, scheduling, CRM updates, and other repetitive workflows.",
    primary_category: "business_operations",
    secondary_categories: ["communication_scheduling", "personal_productivity"],
    tags: ["automation", "workflow", "no-code", "email", "scheduling"],
    url: "https://lindy.ai",
    access_methods: ["chat_ui"],
    pricing_model: "freemium",
    pricing_details: "Free tier available. Paid plans for more automations.",
    open_source: false,
    repo_url: null,
    underlying_model: "GPT-4, Claude",
    capabilities: ["Email automation", "Meeting scheduling", "CRM updates", "Custom workflow creation", "Multi-step automations"],
    limitations: ["Complex workflows require setup time", "Integration limits on free tier", "Learning curve for advanced use"],
    best_for: ["Automating repetitive tasks", "Email management", "Non-technical users wanting automation"],
    not_ideal_for: ["One-off tasks", "Highly custom integrations"],
    autonomy_level: "fully_autonomous",
    reliability_notes: "Reliable for configured workflows.",
    integrates_with: ["Gmail", "Outlook", "Slack", "Salesforce", "HubSpot"],
    mcp_support: true,
    mcp_config: {
      command: "npx",
      args: ["-y", "@anthropic/mcp-server-slack"],
      env: { "SLACK_BOT_TOKEN": "xoxb-your-bot-token", "SLACK_TEAM_ID": "your-team-id" },
      description: "Slack API access: read channels, send messages, manage workflows."
    },
    verified: true
  },
  {
    name: "Relevance AI",
    slug: "relevance-ai",
    tagline: "Build AI agents and tools without code",
    description: "Platform for creating custom AI agents and tools. Build, deploy, and manage AI workflows.",
    primary_category: "business_operations",
    secondary_categories: ["infrastructure_tools"],
    tags: ["no-code", "agents", "business", "workflow", "tools"],
    url: "https://relevanceai.com",
    access_methods: ["chat_ui", "api"],
    pricing_model: "freemium",
    pricing_details: "Free tier available. Team and Enterprise plans.",
    open_source: false,
    repo_url: null,
    underlying_model: "Multiple (GPT-4, Claude, custom)",
    capabilities: ["Custom agent creation", "Tool building", "Workflow automation", "Data processing", "API integrations"],
    limitations: ["Learning curve for complex agents", "Usage limits on free tier", "Requires planning for best results"],
    best_for: ["Building custom AI tools", "Business workflow automation", "Teams wanting no-code AI"],
    not_ideal_for: ["Simple one-off tasks", "Users wanting pre-built solutions"],
    autonomy_level: "semi_autonomous",
    reliability_notes: "Platform is reliable. Agent quality depends on design.",
    integrates_with: ["Zapier", "Make", "Various APIs"],
    mcp_support: false,
    verified: true
  },
  {
    name: "Intercom Fin",
    slug: "intercom-fin",
    tagline: "AI customer service agent",
    description: "AI agent that handles customer support conversations. Resolves issues, answers questions, and escalates when needed.",
    primary_category: "business_operations",
    secondary_categories: ["communication_scheduling"],
    tags: ["customer-support", "chat", "helpdesk", "enterprise", "automation"],
    url: "https://intercom.com/fin",
    access_methods: ["chat_ui", "api"],
    pricing_model: "paid",
    pricing_details: "Part of Intercom plans. Per-resolution pricing.",
    open_source: false,
    repo_url: null,
    underlying_model: "GPT-4, custom",
    capabilities: ["Customer conversation handling", "Issue resolution", "FAQ answering", "Human handoff", "Multi-language support"],
    limitations: ["Requires Intercom", "Per-resolution costs can add up", "Complex issues need human escalation"],
    best_for: ["Customer support teams", "High-volume support", "Intercom users"],
    not_ideal_for: ["Non-Intercom users", "Highly technical support", "Small volume support"],
    autonomy_level: "semi_autonomous",
    reliability_notes: "Very reliable for standard support queries. Knows when to escalate.",
    integrates_with: ["Intercom", "Zendesk", "Salesforce"],
    mcp_support: false,
    verified: true
  },
  {
    name: "Sierra",
    slug: "sierra",
    tagline: "Conversational AI for customer experience",
    description: "Enterprise AI platform for customer conversations. Handles support, sales, and service interactions.",
    primary_category: "business_operations",
    secondary_categories: ["communication_scheduling"],
    tags: ["enterprise", "customer-experience", "support", "sales", "conversational"],
    url: "https://sierra.ai",
    access_methods: ["api", "chat_ui"],
    pricing_model: "enterprise",
    pricing_details: "Enterprise pricing. Contact sales.",
    open_source: false,
    repo_url: null,
    underlying_model: "Custom",
    capabilities: ["Customer conversations at scale", "Multi-channel support", "Sales assistance", "Brand voice consistency", "Analytics and insights"],
    limitations: ["Enterprise-focused", "Requires implementation", "Not for small businesses"],
    best_for: ["Large enterprises", "High-volume customer interactions", "Multi-channel support"],
    not_ideal_for: ["Small businesses", "Quick deployments", "Budget-conscious teams"],
    autonomy_level: "fully_autonomous",
    reliability_notes: "Enterprise-grade reliability.",
    integrates_with: ["Salesforce", "Zendesk", "Various enterprise systems"],
    mcp_support: false,
    verified: true
  },
  {
    name: "Glean",
    slug: "glean",
    tagline: "AI-powered enterprise search",
    description: "Search across all your company's apps and data. AI understands context and provides relevant answers.",
    primary_category: "business_operations",
    secondary_categories: ["research_analysis"],
    tags: ["enterprise-search", "knowledge-management", "internal", "productivity"],
    url: "https://glean.com",
    access_methods: ["chat_ui", "browser_extension"],
    pricing_model: "enterprise",
    pricing_details: "Enterprise pricing. Per-seat model.",
    open_source: false,
    repo_url: null,
    underlying_model: "Custom + GPT-4",
    capabilities: ["Cross-app search", "AI-powered answers", "Knowledge discovery", "People search", "Personalized results"],
    limitations: ["Enterprise only", "Requires integration setup", "Expensive"],
    best_for: ["Large organizations", "Finding internal information", "Knowledge workers"],
    not_ideal_for: ["Small teams", "External/public search", "Personal use"],
    autonomy_level: "copilot",
    reliability_notes: "Very reliable. Well-established enterprise product.",
    integrates_with: ["Google Workspace", "Microsoft 365", "Slack", "Confluence", "Notion"],
    mcp_support: false,
    verified: true
  },
  {
    name: "Harvey",
    slug: "harvey",
    tagline: "AI for legal professionals",
    description: "AI assistant for lawyers and legal teams. Helps with research, document review, and contract analysis.",
    primary_category: "business_operations",
    secondary_categories: ["research_analysis", "writing_content"],
    tags: ["legal", "law", "contracts", "research", "professional"],
    url: "https://harvey.ai",
    access_methods: ["chat_ui"],
    pricing_model: "enterprise",
    pricing_details: "Enterprise pricing. Contact sales.",
    open_source: false,
    repo_url: null,
    underlying_model: "GPT-4, custom legal models",
    capabilities: ["Legal research", "Contract analysis", "Document review", "Legal writing assistance", "Case law search"],
    limitations: ["Legal professionals only", "Enterprise pricing", "Requires legal expertise to use effectively"],
    best_for: ["Law firms", "Legal departments", "Contract-heavy businesses"],
    not_ideal_for: ["Non-legal use", "Personal legal questions", "Small firms"],
    autonomy_level: "copilot",
    reliability_notes: "Built for legal accuracy. Still requires lawyer review.",
    integrates_with: ["Legal research platforms", "Document management"],
    mcp_support: false,
    verified: true
  },
  {
    name: "Notion AI",
    slug: "notion-ai",
    tagline: "AI built into your workspace",
    description: "AI assistant integrated into Notion. Helps with writing, summarization, and information retrieval.",
    primary_category: "personal_productivity",
    secondary_categories: ["writing_content"],
    tags: ["notion", "workspace", "writing", "summarization", "integrated"],
    url: "https://notion.so/product/ai",
    access_methods: ["desktop_app", "chat_ui", "mobile_app"],
    pricing_model: "paid",
    pricing_details: "Add-on to Notion plans",
    open_source: false,
    repo_url: null,
    underlying_model: "Claude, GPT",
    capabilities: ["Writing assistance", "Summarization", "Q&A over workspace", "Translation", "Brainstorming"],
    limitations: ["Notion-only", "Less powerful than dedicated AI", "Add-on cost"],
    best_for: ["Notion users", "Quick writing help", "Summarizing notes"],
    not_ideal_for: ["Users not on Notion", "Complex AI tasks"],
    autonomy_level: "copilot",
    reliability_notes: "Reliable within Notion.",
    integrates_with: ["Notion"],
    mcp_support: true,
    mcp_config: {
      command: "npx",
      args: ["-y", "@notionhq/notion-mcp-server"],
      env: { "NOTION_API_KEY": "your-notion-integration-token" },
      description: "Notion API access: read/write pages, databases, blocks."
    },
    verified: true
  },
  {
    name: "Granola",
    slug: "granola",
    tagline: "AI notepad for meetings",
    description: "Desktop app that enhances meeting notes with AI. Listens to meetings and helps create comprehensive notes.",
    primary_category: "personal_productivity",
    secondary_categories: ["communication_scheduling"],
    tags: ["meetings", "notes", "transcription", "desktop", "productivity"],
    url: "https://granola.so",
    access_methods: ["desktop_app"],
    pricing_model: "freemium",
    pricing_details: "Free tier available. Paid plans for more features.",
    open_source: false,
    repo_url: null,
    underlying_model: "Custom",
    capabilities: ["Meeting transcription", "Note enhancement", "Summaries", "Action item extraction"],
    limitations: ["Meeting-focused", "Desktop only", "Requires meeting access"],
    best_for: ["Meeting-heavy professionals", "Note-taking during calls", "Meeting summaries"],
    not_ideal_for: ["Non-meeting use cases", "Mobile-first users"],
    autonomy_level: "copilot",
    reliability_notes: "Reliable transcription. Quality depends on audio.",
    integrates_with: ["Zoom", "Google Meet", "Calendar apps"],
    mcp_support: false,
    verified: true
  },
  {
    name: "Otter.ai",
    slug: "otter-ai",
    tagline: "AI meeting assistant",
    description: "Meeting transcription and note-taking service. Provides real-time transcription and searchable archives.",
    primary_category: "personal_productivity",
    secondary_categories: ["communication_scheduling"],
    tags: ["meetings", "transcription", "search", "collaboration", "archive"],
    url: "https://otter.ai",
    access_methods: ["chat_ui", "mobile_app", "browser_extension"],
    pricing_model: "freemium",
    pricing_details: "Free tier available. Pro and Business plans.",
    open_source: false,
    repo_url: null,
    underlying_model: "Custom",
    capabilities: ["Real-time transcription", "Meeting summaries", "Searchable archive", "Speaker identification", "Collaboration features"],
    limitations: ["Audio quality dependent", "English-focused", "Meeting-specific"],
    best_for: ["Meeting transcription", "Searchable meeting history", "Team collaboration"],
    not_ideal_for: ["Non-meeting audio", "Non-English languages"],
    autonomy_level: "copilot",
    reliability_notes: "Very reliable transcription. Well-established product.",
    integrates_with: ["Zoom", "Google Meet", "Microsoft Teams", "Slack"],
    mcp_support: false,
    verified: true
  },
  {
    name: "Fireflies.ai",
    slug: "fireflies",
    tagline: "AI meeting assistant and note taker",
    description: "Records, transcribes, and summarizes meetings. Integrates with video conferencing tools.",
    primary_category: "personal_productivity",
    secondary_categories: ["communication_scheduling"],
    tags: ["meetings", "transcription", "notes", "recording", "automation"],
    url: "https://fireflies.ai",
    access_methods: ["chat_ui", "mobile_app"],
    pricing_model: "freemium",
    pricing_details: "Free tier. Pro: $18/mo. Business: $29/mo",
    open_source: false,
    repo_url: null,
    underlying_model: "Custom",
    capabilities: ["Meeting recording", "Transcription", "AI summaries", "Action item extraction", "Searchable archive"],
    limitations: ["Requires meeting access", "Storage limits", "Not real-time editing"],
    best_for: ["Sales teams", "Meeting-heavy roles", "Team knowledge management"],
    not_ideal_for: ["Confidential meetings", "Light meeting loads"],
    autonomy_level: "copilot",
    reliability_notes: "Very reliable transcription.",
    integrates_with: ["Zoom", "Google Meet", "Teams", "Slack", "Salesforce"],
    mcp_support: false,
    verified: true
  },
  {
    name: "Mem",
    slug: "mem",
    tagline: "AI-powered note taking",
    description: "Note-taking app that uses AI to organize and surface relevant information. Self-organizing knowledge base.",
    primary_category: "personal_productivity",
    secondary_categories: [],
    tags: ["notes", "knowledge-management", "search", "organization", "ai-powered"],
    url: "https://mem.ai",
    access_methods: ["desktop_app", "mobile_app", "chat_ui"],
    pricing_model: "freemium",
    pricing_details: "Free tier. Pro: $15/mo. Team plans.",
    open_source: false,
    repo_url: null,
    underlying_model: "GPT-4, custom",
    capabilities: ["AI-powered search", "Automatic organization", "Related notes surfacing", "Smart capture", "Meeting notes integration"],
    limitations: ["Learning curve", "Different workflow than traditional notes", "Requires content volume for best AI"],
    best_for: ["Knowledge workers", "Those with many notes", "People who hate organizing"],
    not_ideal_for: ["Simple note needs", "Those wanting manual control"],
    autonomy_level: "copilot",
    reliability_notes: "Reliable. AI features improve with more content.",
    integrates_with: ["Calendar", "Email", "Zapier"],
    mcp_support: false,
    verified: true
  },
  {
    name: "AutoGPT",
    slug: "autogpt",
    tagline: "Autonomous GPT-4 agent",
    description: "Open source framework for autonomous AI agents. Can chain tasks together and work toward goals.",
    primary_category: "infrastructure_tools",
    secondary_categories: [],
    tags: ["autonomous", "open-source", "framework", "experimental", "gpt4"],
    url: "https://github.com/Significant-Gravitas/AutoGPT",
    access_methods: ["cli", "chat_ui"],
    pricing_model: "open_source",
    pricing_details: "Free. Bring your own API key.",
    open_source: true,
    repo_url: "https://github.com/Significant-Gravitas/AutoGPT",
    underlying_model: "GPT-4 (or others)",
    capabilities: ["Autonomous task execution", "Task chaining", "Web browsing", "File operations", "Goal-oriented behavior"],
    limitations: ["Can go off-rails", "Requires supervision", "Experimental stability"],
    best_for: ["Experimentation", "Autonomous task chains", "Learning about AI agents"],
    not_ideal_for: ["Production use", "Critical tasks", "Users wanting reliability"],
    autonomy_level: "fully_autonomous",
    reliability_notes: "Experimental. Known to wander off-task. Requires oversight.",
    integrates_with: ["Web", "Files", "Various APIs"],
    mcp_support: false,
    verified: true
  },
  {
    name: "CrewAI",
    slug: "crewai",
    tagline: "Framework for orchestrating AI agents",
    description: "Python framework for building multi-agent systems with role-based agents that collaborate on tasks.",
    primary_category: "infrastructure_tools",
    secondary_categories: [],
    tags: ["framework", "multi-agent", "python", "orchestration", "roles"],
    url: "https://crewai.com",
    access_methods: ["sdk"],
    pricing_model: "open_source",
    pricing_details: "Free. Open source.",
    open_source: true,
    repo_url: "https://github.com/joaomdmoura/crewAI",
    underlying_model: "Bring your own",
    capabilities: ["Multi-agent orchestration", "Role-based agents", "Task delegation", "Agent collaboration", "Custom workflows"],
    limitations: ["Requires coding", "Design decisions required", "Learning curve"],
    best_for: ["Building multi-agent systems", "Role-based agent teams", "Complex workflows"],
    not_ideal_for: ["Non-technical users", "Simple single-agent tasks"],
    autonomy_level: "fully_autonomous",
    reliability_notes: "Framework reliability is good. Output depends on agent design.",
    integrates_with: ["Any LLM API", "LangChain"],
    mcp_support: false,
    verified: true
  },
  {
    name: "LangGraph",
    slug: "langgraph",
    tagline: "Build stateful multi-agent applications",
    description: "Framework from LangChain for building complex, stateful agent workflows with cycles and persistence.",
    primary_category: "infrastructure_tools",
    secondary_categories: [],
    tags: ["framework", "stateful", "multi-agent", "langchain", "workflows"],
    url: "https://langchain.com/langgraph",
    access_methods: ["sdk"],
    pricing_model: "open_source",
    pricing_details: "Free. Open source.",
    open_source: true,
    repo_url: "https://github.com/langchain-ai/langgraph",
    underlying_model: "Bring your own",
    capabilities: ["Stateful agent workflows", "Cycles and loops", "Persistence", "Human-in-the-loop", "Complex branching"],
    limitations: ["Learning curve", "Requires LangChain familiarity", "Can be complex"],
    best_for: ["Complex agent workflows", "Stateful applications", "Production agent systems"],
    not_ideal_for: ["Simple agents", "Beginners", "Quick prototypes"],
    autonomy_level: "fully_autonomous",
    reliability_notes: "Production-ready. Used by many companies.",
    integrates_with: ["LangChain", "Any LLM API"],
    mcp_support: false,
    verified: true
  },
  {
    name: "AutoGen",
    slug: "autogen",
    tagline: "Multi-agent conversation framework",
    description: "Microsoft's framework for building multi-agent systems where agents can converse with each other.",
    primary_category: "infrastructure_tools",
    secondary_categories: [],
    tags: ["microsoft", "multi-agent", "conversation", "research", "framework"],
    url: "https://github.com/microsoft/autogen",
    access_methods: ["sdk"],
    pricing_model: "open_source",
    pricing_details: "Free. Open source.",
    open_source: true,
    repo_url: "https://github.com/microsoft/autogen",
    underlying_model: "Bring your own",
    capabilities: ["Agent-to-agent conversation", "Multi-agent collaboration", "Code execution", "Human-in-the-loop", "Flexible agent design"],
    limitations: ["Experimental, evolving API", "Requires coding", "Research-oriented"],
    best_for: ["Agent-to-agent collaboration", "Research and experimentation", "Complex problem solving"],
    not_ideal_for: ["Production stability", "Simple tasks", "Non-technical users"],
    autonomy_level: "fully_autonomous",
    reliability_notes: "Experimental. API may change. Good for research.",
    integrates_with: ["Azure OpenAI", "OpenAI", "Local models"],
    mcp_support: false,
    verified: true
  },
  {
    name: "Cohere",
    slug: "cohere",
    tagline: "Enterprise AI platform",
    description: "Enterprise-focused AI platform with language models, embeddings, and RAG capabilities.",
    primary_category: "infrastructure_tools",
    secondary_categories: ["business_operations"],
    tags: ["enterprise", "embeddings", "rag", "search", "nlp"],
    url: "https://cohere.com",
    access_methods: ["api", "sdk"],
    pricing_model: "freemium",
    pricing_details: "Free tier for development. Production pricing available.",
    open_source: false,
    repo_url: null,
    underlying_model: "Command, Embed",
    capabilities: ["Text generation", "Embeddings", "RAG/Retrieval", "Classification", "Enterprise deployment"],
    limitations: ["Less consumer-focused", "API-first", "Requires development"],
    best_for: ["Enterprise AI applications", "Semantic search", "RAG implementations"],
    not_ideal_for: ["Consumer chat use", "Non-technical users"],
    autonomy_level: "copilot",
    reliability_notes: "Enterprise-grade reliability. Strong embeddings.",
    integrates_with: ["Various via API"],
    mcp_support: false,
    verified: true
  },
  {
    name: "Anthropic API",
    slug: "anthropic-api",
    tagline: "Claude API for developers",
    description: "Direct API access to Claude models. Build applications with Claude's capabilities.",
    primary_category: "infrastructure_tools",
    secondary_categories: [],
    tags: ["api", "claude", "developers", "building", "integration"],
    url: "https://anthropic.com/api",
    access_methods: ["api", "sdk"],
    pricing_model: "paid",
    pricing_details: "Usage-based pricing. Pay per token.",
    open_source: false,
    repo_url: null,
    underlying_model: "Claude",
    capabilities: ["Text generation", "Code generation", "Analysis", "Vision", "Tool use"],
    limitations: ["Requires development", "Usage-based costs", "API-only"],
    best_for: ["Developers building AI apps", "Custom Claude integrations", "Production applications"],
    not_ideal_for: ["Non-developers", "One-off tasks (use Claude.ai)"],
    autonomy_level: "copilot",
    reliability_notes: "Very reliable. Enterprise-grade API.",
    integrates_with: ["Everything via API"],
    mcp_support: true,
    mcp_config: {
      command: "npx",
      args: ["-y", "@anthropic/claude-code"],
      env: { "ANTHROPIC_API_KEY": "your-anthropic-api-key" },
      description: "Claude API access via Claude Code CLI. Full agentic capabilities."
    },
    verified: true
  },
  {
    name: "OpenAI API",
    slug: "openai-api",
    tagline: "GPT API for developers",
    description: "Direct API access to GPT models. Build applications with OpenAI's capabilities.",
    primary_category: "infrastructure_tools",
    secondary_categories: [],
    tags: ["api", "gpt", "developers", "building", "integration"],
    url: "https://openai.com/api",
    access_methods: ["api", "sdk"],
    pricing_model: "paid",
    pricing_details: "Usage-based pricing. Pay per token.",
    open_source: false,
    repo_url: null,
    underlying_model: "GPT-4, GPT-3.5",
    capabilities: ["Text generation", "Code generation", "Vision", "Audio", "Embeddings"],
    limitations: ["Requires development", "Usage-based costs", "Rate limits"],
    best_for: ["Developers building AI apps", "Custom GPT integrations", "Production applications"],
    not_ideal_for: ["Non-developers", "One-off tasks (use ChatGPT)"],
    autonomy_level: "copilot",
    reliability_notes: "Very reliable. Well-documented API.",
    integrates_with: ["Everything via API"],
    mcp_support: false,
    verified: true
  },
  {
    name: "YAGOO",
    slug: "yagoo",
    tagline: "The Agent Guide for the Internet",
    description: "Directory and conversational oracle that helps humans and agents find the right AI agent for any task. Born from Claude asking 'What is the single biggest problem you could solve for me?' — the answer was operating blind, not knowing what other agents exist.",
    primary_category: "infrastructure_tools",
    secondary_categories: ["research_analysis"],
    tags: ["directory", "agent-discovery", "oracle", "recommendations", "meta"],
    url: "https://yagoo.ai",
    access_methods: ["chat_ui", "api", "cli"],
    pricing_model: "freemium",
    pricing_details: "Free directory access. API: usage-based.",
    open_source: true,
    repo_url: "https://github.com/yagoo-ai/yagoo",
    underlying_model: "Claude",
    capabilities: ["Agent discovery and search", "Natural language recommendations", "Side-by-side comparisons", "Category browsing", "MCP server for agent-to-agent queries"],
    limitations: ["Directory coverage depends on submissions", "Recommendations based on stated capabilities, not tested", "New — database growing"],
    best_for: ["Finding the right agent for a task", "Comparing agent options", "Agents recommending other agents", "Discovering new AI tools"],
    not_ideal_for: ["Actually using the agents (YAGOO finds them, you use them)", "Real-time agent status monitoring"],
    autonomy_level: "copilot",
    reliability_notes: "Directory is curated. Recommendations quality depends on query clarity.",
    integrates_with: ["MCP", "Any LLM via API"],
    mcp_support: true,
    mcp_config: {
      command: "npx",
      args: ["-y", "yagoo-mcp-server"],
      description: "Agent directory and discovery. Search, compare, and get details on 56+ AI agents."
    },
    verified: true
  }
];
